/*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package GUI;
//
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//
///**
// *
// * @author Asus
// */
//public class FRMDanhSach extends javax.swing.JFrame implements ActionListener{
//
//    /**
//     * Creates new form FRMDanhSach
//     */
//    public FRMDanhSach() {
//        initComponents();
//        setLocationRelativeTo(null);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jLabel2 = new javax.swing.JLabel();
//        jButtonQuayLai = new javax.swing.JButton();
//        jButtonChonPhong = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
//        jLabel2.setText("DANH SÁCH CÁC PHÒNG");
//
//        jButtonQuayLai.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\undo.png")); // NOI18N
//
//        jButtonChonPhong.setIcon(new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\checked.png")); // NOI18N
//
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null, null, null},
//                {null, null, null, null, null, null},
//                {null, null, null, null, null, null},
//                {null, null, null, null, null, null}
//            },
//            new String [] {
//                "Mã phòng", "Loại phòng", "Sức chứa", "Giá phòng", "Mô tả", "Tình trạng"
//            }
//        ));
//        jScrollPane1.setViewportView(jTable1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(63, 63, 63)
//                .addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(167, 167, 167)
//                .addComponent(jButtonChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(63, 63, 63))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                    .addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jButtonChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(14, Short.MAX_VALUE))
//        );
//        jButtonQuayLai.addActionListener(this);
//        jButtonChonPhong.addActionListener(this);
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FRMDanhSach().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton jButtonChonPhong;
//    private javax.swing.JButton jButtonQuayLai;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTable jTable1;
//    // End of variables declaration//GEN-END:variables
//	@Override
//	public void actionPerformed(ActionEvent e) {
//		// TODO Auto-generated method stub
//		Object o = e.getSource();
//		if(o.equals(jButtonQuayLai)) {
//			FRMQuanLi quanLi = new FRMQuanLi();
//	         quanLi.setVisible(true);
//		}
//		else if(o.equals(jButtonChonPhong)) {
//			this.setVisible(false);
//		}
//	}
//}

// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import Connect.ConnectDB;
import Dao.DAOPhong;
import Entity.Phong;

/**
 *
 * @author Asus
 */
public class FRMDanhSach extends javax.swing.JFrame implements ActionListener, MouseListener, WindowListener {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3550166278943599643L;
	private DAOPhong daoPhong = new DAOPhong();
	private boolean loaiDS;// VIP =1, Thuong = 0
	private String maPhong = "haha";

	/**
	 * Creates new form FRMDanhSach
	 */
	public FRMDanhSach() {
		initComponents();
		setLocationRelativeTo(null);
		setDefaultCloseOperation(HIDE_ON_CLOSE);
	}

	public FRMDanhSach(String loaiPhong) {
		if (loaiPhong.equals("VIP"))
			this.loaiDS = true;
		else
			this.loaiDS = false;
		initComponents();
		setLocationRelativeTo(null);
		setDefaultCloseOperation(HIDE_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		try {
			ConnectDB.getinstance().connect();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		jLabel2 = new javax.swing.JLabel();
		jButtonQuayLai = new javax.swing.JButton();
		jButtonChonPhong = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
		jLabel2.setText("DANH SÁCH CÁC PHÒNG");

		jButtonQuayLai.setIcon(
				new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\undo.png")); // NOI18N

		jButtonChonPhong.setIcon(
				new javax.swing.ImageIcon("D:\\PhatTrienUngDung\\baiTapLonCKPTUD\\baiTapLonCKPTUD\\iCon\\checked.png")); // NOI18N

// TABLE	TABLE	TABLE	TABLE	TABLE	

//		jTable1.setModel(new javax.swing.table.DefaultTableModel(
//				new String[] { "Mã phòng", "Loại phòng", "Sức chứa", "Giá phòng", "Mô tả", "Tình trạng" }, 0));
//		jScrollPane1.setViewportView(jTable1);
		String header[] = { "Mã phòng", "Loại phòng", "Sức chứa", "Giá phòng", "Mô tả", "Tình trạng" };
		modelPhong = new DefaultTableModel(header, 0);
		jTable1 = new JTable(modelPhong);
		jTable1.setDefaultEditor(Object.class, null);
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(63, 63, 63)
						.addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(167, 167, 167).addComponent(jButtonChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE,
								54, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(63, 63, 63)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
						.addComponent(jButtonQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButtonChonPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 53,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(14, Short.MAX_VALUE)));
		jButtonQuayLai.addActionListener(this);
		jButtonChonPhong.addActionListener(this);
		jTable1.addMouseListener(this);
		pack();
		loadDS();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FRMDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FRMDanhSach().setVisible(true);
			}
		});
	}

	private void loadDS() {
		ArrayList<Phong> dsPhong = new ArrayList<Phong>();
		if (loaiDS)// load phong vip
			dsPhong = daoPhong.getPhongVIPTrong();
		else
			dsPhong = daoPhong.getPhongThuongTrong();
		if (dsPhong != null) {
//			String header[]= { "Mã phòng", "Loại phòng", "Sức chứa", "Giá phòng", "Mô tả", "Tình trạng" };
			for (Phong p : dsPhong)
				modelPhong.addRow(new Object[] { p.getMaPhong(), p.getLoaiPhong().getTenLoaiPhong(), p.getSucChua(),
						p.getGiaPhong(), p.getMoTa(), p.getTinhTrangPhong() });
		}
	}

	public String getMaPhong() {
		return maPhong;
	}

	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if (o.equals(jButtonQuayLai)) {
			// sửa sau
			FRMQuanLi quanLi = new FRMQuanLi(null);
			quanLi.setVisible(true);
		} else if (o.equals(jButtonChonPhong)) {
			this.setVisible(false);
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonChonPhong;
	private javax.swing.JButton jButtonQuayLai;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private DefaultTableModel modelPhong;

	@Override
	public void mouseClicked(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if (o.equals(jTable1)) {
			if (e.getClickCount() == 2 && !e.isConsumed()) {
				e.consume();
				int row = jTable1.getSelectedRow();
				if (row > -1) {
					maPhong = jTable1.getValueAt(row, 0).toString();
				}
			}
		}
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowOpened(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowClosing(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowClosed(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowIconified(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowDeiconified(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowActivated(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void windowDeactivated(WindowEvent e) {
		// TODO Auto-generated method stub

	}

	// End of variables declaration//GEN-END:variables
}

